name:                html-parse-util
version:             0.2.0
homepage:            https://gitlab.com/slotThe/html-parse-utils
synopsis:            Utility functions for working with html-parse
license:             AGPL-3
author:              Neil Mitchell (TagSoup), Tony Zorman (port to html-parse)
maintainer:          Tony Zorman <soliditsallgood@mailbox.org>
copyright:           2020–2022  Tony Zorman

default-extensions:
  - OverloadedStrings
  - LambdaCase

ghc-options:
  -Weverything
  -Wno-implicit-prelude
  -Wno-missing-import-lists
  -Wno-unused-packages
  -Wno-missing-safe-haskell-mode
  -Wno-all-missed-specialisations
  -Wno-unsafe
  -Wno-prepositive-qualified-module
  -O2

dependencies:
  - base       >= 4.7     && < 5
  - text       >= 1.2     && < 1.3
  - html-parse >= 0.2.0.2 && < 0.3
  - attoparsec >= 0.13    && < 0.15

library:
  source-dirs: lib
