name:                html-parse-utils
version:             0.1.0.0
homepage:            https://gitlab.com/slotThe/html-parse-utils
synopsis:            Utility functions for working with html-parse
license:             AGPL-3
author:              Neil Mitchell (TagSoup), Tony Zorman (port to html-parse)
maintainer:          Tony Zorman <soliditsallgood@mailbox.org>
copyright:           2020  Tony Zorman

default-extensions:
  - OverloadedStrings
  - LambdaCase

ghc-options:
  -O2
  -Wall
  -Wcompat
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wredundant-constraints
  -Widentities
  -Wmissing-local-signatures
  -Wmissing-export-lists
  -Wmissed-specialisations

dependencies:
  - base         >= 4.7     && < 5
  - text         >= 1.2     && < 1.3
  - html-parse   >= 0.2.0.2 && < 0.3

library:
  source-dirs: lib
