name:                html-parse-util
version:             0.2.2
github:              slotThe/html-parse-util
synopsis:            Utility functions for working with html-parse
description:         See README.md <https://gitlab.com/slotThe/html-parse-utils/-/blob/master/README.md here>
category:            Text, XML
license:             BSD3
author:              Neil Mitchell (TagSoup), Tony Zorman (port to html-parse)
maintainer:          soliditsallgood@mailbox.org
copyright:           2006–2019  Neil Mitchell,
                     2020–2022  Tony Zorman

extra-source-files:
  - README.md
  - CHANGELOG.md

default-extensions:
  - OverloadedStrings
  - LambdaCase

ghc-options:
  -Weverything
  -Wno-implicit-prelude
  -Wno-missing-import-lists
  -Wno-unused-packages
  -Wno-missing-safe-haskell-mode
  -Wno-all-missed-specialisations
  -Wno-unsafe
  -Wno-prepositive-qualified-module

dependencies:
  - base       >= 4.7     && < 5
  - text       >= 1.2     && < 1.3
  - html-parse >= 0.2.0.2 && < 0.3
  - attoparsec >= 0.13    && < 0.15

library:
  source-dirs: lib
